---
permalink: technical-reports/monitor/index.html 
sidebar: sidebar 
keywords: monitoring, storagegrid 
summary: 'Découvrez comment comprendre NetApp StorageGRID, ses conditions d"erreur et comment le surveiller efficacement à l"aide d"applications externes telles que Splunk.' 
---
= Introduction à la surveillance StorageGRID
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../../media/


[role="lead"]
Découvrez comment contrôler votre système StorageGRID à l'aide d'applications externes telles que Splunk.

La surveillance efficace du stockage objet NetApp StorageGRID permet aux administrateurs de répondre rapidement aux problèmes urgents et d'ajouter de manière proactive des ressources pour gérer la croissance des workloads. Ce rapport fournit des conseils généraux sur la façon de surveiller les mesures clés et d'exploiter les applications de surveillance externes. Il est destiné à compléter le guide de surveillance et de dépannage existant.

Un déploiement NetApp StorageGRID se compose généralement de plusieurs sites et de nombreux nœuds qui créent un système de stockage objet distribué et tolérant aux pannes. Dans un système de stockage distribué et résilient tel que StorageGRID, il est normal que des conditions d'erreur existent alors que la grille continue de fonctionner normalement. En tant qu'administrateur, le défi consiste à comprendre le seuil auquel les conditions d'erreur (telles que les nœuds en panne) constituent un problème qui doit être immédiatement résolu par rapport aux informations à analyser. En analysant les données d'StorageGRID, vous pouvez analyser votre charge de travail et prendre des décisions avisées, notamment concernant l'ajout de ressources.

StorageGRID fournit une excellente documentation qui analyse le sujet de la surveillance. Ce rapport part du principe que vous connaissez StorageGRID et que vous avez consulté la documentation correspondante. Au lieu de répéter ces informations, nous nous référons à la documentation produit tout au long de ce guide. La documentation des produits StorageGRID est disponible en ligne et au format PDF.

L'objectif de ce document est de compléter la documentation produit et de découvrir comment contrôler votre système StorageGRID à l'aide d'applications externes, telles que Splunk.



== Sources de données

Pour réussir la surveillance de NetApp StorageGRID, il est important de savoir où collecter des données sur l'état et les opérations de votre système StorageGRID.

* *Interface utilisateur Web et tableau de bord.* Le gestionnaire de grille StorageGRID présente une vue de haut niveau des informations que vous, en tant qu'administrateur, devez voir dans une présentation logique. En tant qu'administrateur, vous pouvez également approfondir les informations de niveau de service pour le dépannage et la collecte des journaux.
* *Journaux d'audit.* StorageGRID conserve des journaux d'audit granulaires des actions des locataires telles que LA COMMANDE PUT, GET et DELETE. Vous pouvez également suivre le cycle de vie d'un objet de l'ingestion à l'application des règles de gestion des données.
* *API métriques.* Les API de l'interface utilisateur sont sous-jacentes à l'interface GMI de StorageGRID. Cette approche vous permet d'extraire des données à l'aide d'outils externes de surveillance et d'analyse.




== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Centre de documentation NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-118/[]
* Accompagnement NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-enable/[]
* Ressources de documentation StorageGRID https://www.netapp.com/data-storage/storagegrid/documentation/[]
* Documentation des produits NetApp https://www.netapp.com/support-and-training/documentation/[]
* NetApp StorageGRID application pour Splunk https://splunkbase.splunk.com/app/3898/#/details[]

