---
sidebar: sidebar 
permalink: technical-reports/ransomware-protection-index.html 
keywords: ransomware attacks, storagegrid, best practices 
summary: Découvrez les attaques par ransomware et comment protéger vos données grâce aux bonnes pratiques de sécurité de StorageGRID. 
---
= Protégez les objets StorageGRID S3 contre les attaques par ransomware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez les attaques par ransomware et comment protéger vos données grâce aux bonnes pratiques de sécurité de StorageGRID.

Le nombre d'attaques par ransomware est en hausse Ce document fournit quelques recommandations sur la protection des données d'objet sur StorageGRID.

Les ransomware représentent aujourd'hui le danger omniprésent dans les data centers. Les ransomwares ont été conçus pour chiffrer les données et les rendre inutilisables par des utilisateurs et des applications qui en dépendent. La protection commence par les défenses habituelles : une mise en réseau renforcée et de solides pratiques de sécurité des utilisateurs. Nous devons ensuite appliquer les pratiques de sécurité de l'accès aux données.

Les ransomwares sont l'une des plus grandes menaces de sécurité. L'équipe NetApp StorageGRID travaille avec nos clients pour garder une longueur d'avance sur ces menaces. Le verrouillage d'objets et la gestion des versions vous permettent de vous protéger contre les modifications indésirables et de restaurer votre système suite à des attaques malveillantes. La sécurité des données est une entreprise multiniveaux, dans laquelle le stockage objet n'est qu'une partie de votre data Center.



== Meilleures pratiques StorageGRID

Pour StorageGRID, les bonnes pratiques en matière de sécurité doivent inclure l'utilisation du protocole HTTPS avec des certificats signés pour la gestion et l'accès aux objets. Créez des comptes utilisateur dédiés aux applications et aux particuliers et n'utilisez pas les comptes root des locataires pour l'accès aux applications ou aux données utilisateur. En d'autres termes, suivez le principe du privilège minimum. Utilisez des groupes de sécurité avec des règles de gestion des identités et des accès (IAM) définies pour régir les droits d'utilisateur et les comptes d'accès spécifiques aux applications et aux utilisateurs. Une fois ces mesures mises en place, vous devez vous assurer que vos données sont protégées. Dans le cas de simple Storage Service (S3), lorsque les objets sont modifiés pour les chiffrer, il est remplacé par l'objet d'origine.



== Méthodes de défense

Le mécanisme principal de protection contre les ransomwares dans l'API S3 consiste à mettre en œuvre le verrouillage objet. Toutes les applications ne sont pas compatibles avec le verrouillage d'objet. Il existe donc deux autres options pour protéger vos objets décrites dans ce rapport : la réplication vers un autre compartiment avec la gestion des versions activée et la gestion des versions avec les règles IAM.



== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Centre de documentation NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-118/[]
* Accompagnement NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-enable/[]
* Documentation des produits NetApp https://www.netapp.com/support-and-training/documentation/[]

