---
sidebar: sidebar 
permalink: technical-reports/bare-metal/index.html 
keywords: install, storagegrid, deploy, bare metal 
summary: Découvrez comment installer StorageGRID sur une grille bare Metal. 
---
= Introduction à l'installation de StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Découvrez comment installer StorageGRID sur des hôtes bare Metal.

Le TR-4882 fournit un ensemble d'instructions pratiques et détaillées qui produit une installation de travail de NetApp StorageGRID. L'installation peut se faire soit sur des serveurs bare Metal, soit sur des machines virtuelles exécutées sur Red Hat Enterprise Linux (RHEL). L'approche consiste à effectuer une installation « optiniée » de six services conteneurisés StorageGRID sur trois machines physiques (ou virtuelles) dans une disposition et une configuration de stockage suggérées. Certains clients peuvent comprendre plus facilement le processus de déploiement en suivant l'exemple de déploiement présenté dans ce rapport technique.

Pour une compréhension plus approfondie de StorageGRID et du processus d'installation, consultez [StorageGRID d'installation, de https://docs.netapp.com/us-en/storagegrid-118/landing-install-upgrade/index.html[] mise à niveau et de correctif] dans la documentation du produit.

Avant de commencer votre déploiement, examinons les exigences de calcul, de stockage et de réseau du logiciel NetApp StorageGRID. StorageGRID s'exécute en tant que service conteneurisé dans Podman ou Docker. Dans ce modèle, certaines exigences font référence au système d'exploitation hôte (le système d'exploitation qui héberge Docker et exécute le logiciel StorageGRID). En outre, certaines ressources sont allouées directement aux conteneurs Docker s'exécutant au sein de chaque hôte. Dans ce déploiement, afin d'optimiser l'utilisation du matériel, nous déployons deux services par hôte physique. Pour plus d'informations, passez à la section suivante, link:prerequisites-install-storagegrid.html["Conditions préalables à l'installation de StorageGRID"].

Les étapes décrites dans ce rapport technique permettent d'effectuer une installation StorageGRID fonctionnelle sur six hôtes bare Metal. Vous disposez désormais d'une grille et d'un réseau client qui fonctionnent, ce qui est utile dans la plupart des scénarios de test.



== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce rapport technique, consultez les ressources de documentation suivantes :

* Centre de documentation NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-118/[]
* Accompagnement NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-enable/[]
* Ressources de documentation StorageGRID https://www.netapp.com/data-storage/storagegrid/documentation/[]
* Documentation des produits NetApp https://www.netapp.com/support-and-training/documentation/[]

