---
sidebar: sidebar 
permalink: technical-reports/bare-metal/node-config-file-storagegrid.html 
keywords: node config, storagegrid 
summary: Apprenez à préparer les fichiers de configuration de nœuds pour StorageGRID. 
---
= Préparez les fichiers de configuration des nœuds pour StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Découvrez comment préparer les fichiers de configuration des nœuds pour StorageGRID.

À un niveau élevé, le processus de configuration des nœuds comprend les étapes suivantes :

.Étapes
. Créez le `/etc/storagegrid/nodes` répertoire sur tous les hôtes.
+
[listing]
----
sudo [root@host1 ~]# mkdir -p /etc/storagegrid/nodes
----
. Créez les fichiers nécessaires par hôte physique pour correspondre à la disposition du type de conteneur/nœud. Dans cet exemple, nous avons créé deux fichiers par hôte physique sur chaque machine hôte.
+

NOTE: Le nom du fichier définit le nom réel du nœud pour l'installation. Par exemple, `dc1-adm1.conf` devient un nœud nommé `dc1-adm1`.

+
-- Host1 :
`dc1-adm1.conf`
`dc1-sn1.conf`

+
-- Host2 :
`dc1-gw1.conf`
`dc1-sn2.conf`

+
-- Host3 :
`dc1-gw2.conf`
`dc1-sn3.conf`





== Préparation des fichiers de configuration du nœud

Les exemples suivants utilisent le `/dev/disk/by-path` format. Vous pouvez vérifier les chemins d'accès corrects en exécutant les commandes suivantes :

[listing]
----
[root@host1 ~]# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda 8:0 0 90G 0 disk
├─sda1 8:1 0 1G 0 part /boot
└─sda2 8:2 0 89G 0 part
├─rhel-root 253:0 0 50G 0 lvm /
├─rhel-swap 253:1 0 9G 0 lvm
└─rhel-home 253:2 0 30G 0 lvm /home
sdb 8:16 0 200G 0 disk /var/lib/docker
sdc 8:32 0 90G 0 disk
sdd 8:48 0 200G 0 disk
sde 8:64 0 200G 0 disk
sdf 8:80 0 4T 0 disk
sdg 8:96 0 4T 0 disk
sdh 8:112 0 4T 0 disk
sdi 8:128 0 90G 0 disk
sr0 11:0 1 1024M 0 rom
----
Et ces commandes :

[listing]
----
[root@host1 ~]# ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:02:01.0-ata-1.0 -> ../../sr0
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:4:0 -> ../../sde
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:5:0 -> ../../sdf
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:6:0 -> ../../sdg
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:8:0 -> ../../sdh
lrwxrwxrwx 1 root root 9 Dec 21 16:42 pci-0000:03:00.0-scsi-0:0:9:0 -> ../../sdi
----


== Exemple pour le nœud d'administration principal

Exemple de nom de fichier :

[listing]
----
/etc/storagegrid/nodes/dc1-adm1.conf
----
Exemple de contenu de fichier :


NOTE: Les chemins de disque peuvent suivre les exemples ci-dessous ou utiliser `/dev/mapper/alias` la dénomination de style. N'utilisez pas de noms de périphériques de blocage tels que `/dev/sdb` , car ils peuvent changer au redémarrage et causer des dommages importants à votre grille.

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Primary
MAXIMUM_RAM = 24g
BLOCK_DEVICE_VAR_LOCAL = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0
BLOCK_DEVICE_AUDIT_LOGS = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0
BLOCK_DEVICE_TABLES = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:4:0
GRID_NETWORK_TARGET = ens192
CLIENT_NETWORK_TARGET = ens224
GRID_NETWORK_IP = 10.193.204.43
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.193.204.1
CLIENT_NETWORK_CONFIG = STATIC
CLIENT_NETWORK_IP = 10.193.205.43
CLIENT_NETWORK_MASK = 255.255.255.0
CLIENT_NETWORK_GATEWAY = 10.193.205.1
----


== Exemple de nœud de stockage

Exemple de nom de fichier :

[listing]
----
/etc/storagegrid/nodes/dc1-sn1.conf
----
Exemple de contenu de fichier :

[listing]
----
NODE_TYPE = VM_Storage_Node
MAXIMUM_RAM = 24g
ADMIN_IP = 10.193.174.43
BLOCK_DEVICE_VAR_LOCAL = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:9:0
BLOCK_DEVICE_RANGEDB_00 = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:5:0
BLOCK_DEVICE_RANGEDB_01 = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:6:0
BLOCK_DEVICE_RANGEDB_02 = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:8:0
GRID_NETWORK_TARGET = ens192
CLIENT_NETWORK_TARGET = ens224
GRID_NETWORK_IP = 10.193.204.44
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.193.204.1
----


== Exemple de nœud de passerelle

Exemple de nom de fichier :

[listing]
----
/etc/storagegrid/nodes/dc1-gw1.conf
----
Exemple de contenu de fichier :

[listing]
----
NODE_TYPE = VM_API_Gateway
MAXIMUM_RAM = 24g
ADMIN_IP = 10.193.204.43
BLOCK_DEVICE_VAR_LOCAL = /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0
GRID_NETWORK_TARGET = ens192
CLIENT_NETWORK_TARGET = ens224
GRID_NETWORK_IP = 10.193.204.47
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.193.204.1
CLIENT_NETWORK_IP = 10.193.205.47
CLIENT_NETWORK_MASK = 255.255.255.0
CLIENT_NETWORK_GATEWAY = 10.193.205.1
----