---
sidebar: sidebar 
permalink: technical-reports/commvault/index.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: 'Explorez les quelques cas d"utilisation des configurations StorageGRID mises en œuvre par les clients et PAR NetApp IT.' 
---
= Sauvegardez et restaurez les données à l'aide de StorageGRID et de CommVault
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
CommVault et NetApp se sont associés pour créer une solution commune de protection des données qui combine le logiciel CommVault Complete Backup and Recovery pour NetApp et le logiciel NetApp StorageGRID pour le stockage cloud. CommVault Complete Backup and Recovery et NetApp StorageGRID proposent des solutions uniques et faciles à utiliser qui s'associent pour répondre aux exigences de croissance rapide des données et à celles de réglementations toujours plus strictes à travers le monde.

De nombreuses entreprises souhaitent migrer leur stockage dans le cloud, faire évoluer leurs systèmes et automatiser leurs règles de conservation des données à long terme. Réputé pour sa résilience, son évolutivité, ses avantages opérationnels et ses économies, le stockage objet basé dans le cloud en fait un choix naturel comme cible pour votre sauvegarde. CommVault et NetApp ont certifié conjointement leur solution combinée en 2014. Depuis, ils ont développé une intégration plus étroite entre leurs deux solutions. Des clients de tous types dans le monde ont adopté la solution combinée CommVault Complete Backup and Recovery and StorageGRID.



== À propos de CommVault et StorageGRID

Le logiciel CommVault Complete Backup and Recovery est une solution haute performance de gestion des données et des informations intégrée, conçue dès le départ sur une plateforme unique et dotée d'une base de code unifiée. Toutes ses fonctions partagent des technologies back-end, offrant ainsi les avantages et avantages inégalés d'une approche entièrement intégrée de protection, de gestion et d'accès à vos données. Le logiciel contient des modules pour protéger, archiver, analyser, répliquer et rechercher vos données. Les modules partagent un ensemble commun de services back-end et de fonctionnalités avancées qui interagissent en toute transparence les uns avec les autres. Cette solution aborde tous les aspects de la gestion des données dans votre entreprise, tout en offrant une évolutivité illimitée et un contrôle sans précédent des données et des informations.

NetApp StorageGRID, en tant que Tier cloud CommVault, est une solution de stockage objet de cloud hybride d'entreprise. Vous pouvez le déployer sur de nombreux sites, que ce soit sur une appliance dédiée ou en tant que déploiement Software-defined. StorageGRID vous permet d'établir des règles de gestion des données qui déterminent le mode de stockage et de protection des données. StorageGRID collecte les informations dont vous avez besoin pour développer et appliquer des règles. Il examine un large éventail de caractéristiques et de besoins, y compris les performances, la durabilité, la disponibilité, l'emplacement géographique, longévité et coût. Elles sont intégralement conservées et protégées lors de leur déplacement entre différents sites et au fur et à mesure du vieillissement.

Le moteur de règles intelligent StorageGRID vous aide à choisir l'une des options suivantes :

* Utiliser le code d'effacement pour sauvegarder les données sur plusieurs sites à des fins de résilience.
* Pour copier des objets vers des sites distants afin de minimiser la latence et le coût du WAN.


Lorsque StorageGRID stocke un objet, vous y accédez en tant qu'objet unique, quel que soit son emplacement et le nombre de copies existantes. Ce comportement est crucial pour la reprise d'activité, car grâce à lui, même si une copie de sauvegarde de vos données est corrompue, StorageGRID peut restaurer vos données.

La conservation des données de sauvegarde dans votre stockage primaire peut s'avérer coûteuse. Avec NetApp StorageGRID, vous libérez de l'espace sur votre stockage primaire en migrant les données de sauvegarde inactives vers StorageGRID, tout en bénéficiant des nombreuses fonctionnalités de StorageGRID. La valeur des données de sauvegarde évolue au fil du temps, tout comme le coût de leur stockage. StorageGRID réduit le coût du stockage primaire tout en augmentant la durabilité des données.



== Fonctionnalités clés

Principales fonctionnalités de la plateforme logicielle CommVault :

* Une solution complète de protection des données prenant en charge tous les principaux systèmes d'exploitation, applications et bases de données sur des serveurs virtuels et physiques, des systèmes NAS, des infrastructures cloud et des appareils mobiles.
* Gestion simplifiée via une console unique : vous pouvez afficher, gérer et accéder à toutes les fonctions, à toutes les données et à toutes les informations de l'entreprise.
* Plusieurs méthodes de protection, notamment la sauvegarde et l'archivage des données, la gestion de snapshots, la réplication des données et l'indexation du contenu à des fins d'e-Discovery.
* Gestion du stockage efficace grâce à la déduplication pour le stockage sur disque et cloud.
* Intégration aux baies de stockage NetApp telles que AFF, FAS, NetApp HCI et E-Series et aux systèmes de stockage scale-out NetApp SolidFire^®^. Intégration également au logiciel NetApp Cloud Volumes ONTAP pour automatiser la création de copies NetApp Snapshot™ indexées sur les applications, sur l'ensemble du portefeuille de stockage NetApp.
* Une gestion complète de l'infrastructure virtuelle qui prend en charge les principaux hyperviseurs virtuels sur site et plateformes d'hyperscaler de cloud public.
* Des fonctionnalités de sécurité avancées pour limiter l'accès aux données stratégiques, fournir des fonctionnalités de gestion granulaire et fournir aux utilisateurs Active Directory un accès Single Sign-on.
* Une gestion des données basée sur des règles qui vous permet de gérer vos données en fonction de vos besoins et non de votre emplacement physique.
* Une expérience utilisateur de pointe qui permet à vos utilisateurs de protéger, de rechercher et de restaurer leurs propres données.
* L'automatisation par API vous permet d'utiliser des outils tiers tels que vRealize Automation ou Service Now pour gérer vos opérations de protection et de récupération des données.


Pour plus de détails sur les charges de travail prises en charge, consultez https://www.commvault.com/supported-technologies["Technologies prises en charge par CommVault"].



== Options de sauvegarde

Lorsque vous implémentez le logiciel CommVault Complete Backup and Recovery avec le stockage cloud, vous disposez de deux options de sauvegarde :

* Sauvegarde sur une cible de disque primaire et sauvegarde également une copie auxiliaire sur un stockage cloud.
* Sauvegarde dans le cloud en tant que cible principale.


Auparavant, le stockage cloud ou objet était considéré comme trop faible pour être utilisé pour la sauvegarde principale. L'utilisation d'une cible de disque primaire a permis aux clients d'accélérer les processus de sauvegarde et de restauration, et de conserver une copie auxiliaire dans le cloud en tant que sauvegarde à froid. StorageGRID est la nouvelle génération de stockage objet. StorageGRID offre des performances élevées et un débit massif, ainsi que des performances et une flexibilité bien supérieures à celles des autres fournisseurs de stockage objet.

Le tableau suivant répertorie les avantages de chaque option de sauvegarde avec StorageGRID :

[cols="1a,1a,1a"]
|===
|  | Sauvegarde principale sur disque et copie auxiliaire sur StorageGRID | Sauvegarde principale vers StorageGRID 


 a| 
Performance
 a| 
Délai de restauration le plus rapide, via un montage en direct ou une restauration en direct : idéal pour les workloads de niveau 0/niveau 1.
 a| 
Ne peut pas être utilisé pour les opérations de montage en direct ou de restauration en direct. Idéal pour les opérations de restauration en streaming et pour la conservation à long terme.



 a| 
Architecture de déploiement
 a| 
Utilisation de la technologie 100 % Flash ou d'un disque mécanique comme premier palier d'atterrissage de sauvegarde. StorageGRID est utilisé comme Tier secondaire.
 a| 
Simplifie le déploiement en utilisant StorageGRID comme cible de sauvegarde complète.



 a| 
Fonctionnalités avancées (restauration en direct)
 a| 
Pris en charge
 a| 
Non pris en charge

|===


== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Centre de documentation StorageGRID 11.8 +
https://docs.netapp.com/us-en/storagegrid-118/[]
* Documentation produit NetApp +
https://docs.netapp.com[]
* Documentation CommVault +
https://documentation.commvault.com/2024/essential/index.html[]

