---
sidebar: sidebar 
permalink: technical-reports/commvault/sizing.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: 'Explorez les quelques cas d"utilisation des configurations StorageGRID mises en œuvre par les clients et PAR NetApp IT.' 
---
= Conseils sur le dimensionnement de StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Pour en savoir plus sur le dimensionnement de votre environnement, consultez vos spécialistes de la protection des données NetApp. Les spécialistes de la protection des données NetApp peuvent utiliser le calculateur de stockage de sauvegarde total CommVault pour estimer les exigences de l'infrastructure de sauvegarde. Cet outil requiert un accès au CommVault Partner Portal. Inscrivez-vous pour y accéder, si nécessaire.



== Entrées de dimensionnement CommVault

Les tâches suivantes peuvent être utilisées pour effectuer la découverte du dimensionnement de la solution de protection des données :

* Identifiez les charges de travail du système ou des applications/bases de données et la capacité frontale correspondante (en téraoctets [To]) à protéger.
* Identifiez le workload de machines virtuelles/fichiers et une capacité front-end similaire (To) à protéger.
* Identifier les exigences de conservation à court et à long terme.
* Identifier le taux de modification quotidien en % pour les datasets/workloads identifiés
* Identification de la croissance des données prévue au cours des 12, 24 et 36 prochains mois
* Définissez les objectifs RTO et RPO pour la protection et la restauration des données en fonction des besoins de l'entreprise.


Lorsque ces informations sont disponibles, le dimensionnement de l'infrastructure de sauvegarde peut être effectué, ce qui entraîne la répartition des capacités de stockage requises.



== Conseils sur le dimensionnement de StorageGRID

Avant d'effectuer le dimensionnement NetApp StorageGRID, tenez compte des aspects suivants de votre charge de travail :

* Capacité exploitable
* Mode WORM
* Taille moyenne des objets
* Exigences en matière de performances
* Règle ILM appliquée


La capacité utilisable doit tenir compte de la taille de la charge de travail de sauvegarde que vous avez basculée vers StorageGRID et du calendrier de conservation.

Le mode WORM sera-t-il activé ou non ? Une fois WORM activé dans CommVault, le verrouillage d'objet est configuré sur StorageGRID. Cela augmente la capacité de stockage objet requise. La capacité requise varie en fonction de la durée de conservation et du nombre de modifications d'objet apportées à chaque sauvegarde.

La taille moyenne d'objet est un paramètre d'entrée qui facilite le dimensionnement des performances dans un environnement StorageGRID. La taille moyenne des objets utilisés pour une charge de travail CommVault dépend du type de sauvegarde.

Le tableau suivant répertorie la taille moyenne des objets par type de sauvegarde et décrit ce que le processus de restauration lit à partir du magasin d'objets :

[cols="1a,1a,1a"]
|===
| Type de sauvegarde | Taille moyenne de l'objet | Restaurer le comportement 


 a| 
Effectuer une copie auxiliaire dans StorageGRID
 a| 
32 MO
 a| 
Lecture complète de l'objet 32 Mo



 a| 
Orienter la sauvegarde vers StorageGRID (déduplication activée)
 a| 
8 MO
 a| 
Lecture aléatoire 1 Mo



 a| 
Dirigez la sauvegarde vers StorageGRID (déduplication désactivée)
 a| 
32 MO
 a| 
Lecture complète de l'objet 32 Mo

|===
En outre, la compréhension de vos besoins en performances pour les sauvegardes complètes et les sauvegardes incrémentielles vous aide à déterminer le dimensionnement des nœuds de stockage StorageGRID. Les méthodes de protection des données de la règle de gestion du cycle de vie des informations (ILM) de StorageGRID déterminent la capacité requise pour stocker les sauvegardes CommVault et affectent le dimensionnement de la grille.

La réplication ILM de StorageGRID est l'un des deux mécanismes utilisés par StorageGRID pour stocker les données en mode objet. Lorsque StorageGRID attribue des objets à une règle ILM de réplication des données, le système crée des copies exactes des données des objets et les stocke sur des nœuds de stockage.

Le codage d'effacement est la deuxième méthode utilisée par StorageGRID pour stocker les données d'objet. Lorsque StorageGRID attribue des objets à une règle ILM configurée pour créer des copies avec code d'effacement, elle coupe les données en mode objet en fragments de données. Il calcule ensuite des fragments de parité supplémentaires et stocke chaque fragment sur un nœud de stockage différent. Lorsqu'un objet est accédé, il est réassemblé à l'aide des fragments stockés. En cas de corruption ou de perte d'un fragment de données ou de parité, l'algorithme de code d'effacement peut recréer ce fragment à l'aide d'un sous-ensemble des fragments de données et de parité restants.

Les deux mécanismes nécessitent différentes quantités de stockage, comme le démontrent ces exemples :

* Si vous stockez deux copies répliquées, la surcharge de stockage double.
* Si vous stockez une copie avec code d'effacement 2+1, votre surconsommation de stockage est multipliée par 1.5.


Pour la solution testée, un déploiement StorageGRID d'entrée de gamme sur un seul site a été utilisé :

* Nœud d'administration : machine virtuelle VMware (VM)
* Équilibreur de charge : VMware VM
* Nœuds de stockage : 4 x SG5712 avec disques de 4 To
* Nœud d'administration principal et nœud de passerelle : machines virtuelles VMware avec des exigences minimales en termes de charge de travail de production


[NOTE]
====
StorageGRID prend également en charge les équilibreurs de charge tiers.

====
StorageGRID est généralement déployé sur deux sites ou plus, avec des règles de protection des données qui répliquent les données afin d'éviter les défaillances au niveau des nœuds et des sites. En sauvegardant vos données sur StorageGRID, elles sont protégées par plusieurs copies ou par un code d'effacement qui sépare et réassemble les données de manière fiable à l'aide d'un algorithme.

Vous pouvez utiliser l'outil de dimensionnement https://fusion.netapp.com["Fusion"] pour dimensionner votre grille.



== Évolutivité

Pour étendre un système NetApp StorageGRID, il est possible d'ajouter du stockage aux nœuds de stockage, d'ajouter de nouveaux nœuds grid à un site déjà en place ou d'ajouter un nouveau site de data Center. Les expansions ne nécessitent aucune interruption du fonctionnement du système.
StorageGRID fait évoluer les performances en utilisant soit des nœuds de performance plus élevée pour les nœuds de stockage, soit l'appliance physique qui exécute l'équilibreur de charge et les nœuds d'administration, soit en ajoutant simplement des nœuds supplémentaires.

[NOTE]
====
Pour plus d'informations sur l'extension du système StorageGRID, reportez-vous à la section https://docs.netapp.com/us-en/storagegrid-118/landing-expand/index.html["Guide d'extension StorageGRID 11.8"].

====