---
sidebar: sidebar 
permalink: technical-reports/commvault/solution-overview.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: 'Explorez les quelques cas d"utilisation des configurations StorageGRID mises en œuvre par les clients et PAR NetApp IT.' 
---
= Présentation de la solution testée
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
La solution testée combine les solutions CommVault et NetApp pour offrir une solution commune puissante.



== Configuration de la solution

Dans la configuration de laboratoire, l'environnement StorageGRID se composait de quatre appliances NetApp StorageGRID SG5712, d'un nœud d'administration principal virtuel et d'un nœud de passerelle virtuelle. L'appliance SG5712 est l'option d'entrée de gamme, une configuration de base. Le choix d'appliances plus performantes, telles que NetApp StorageGRID SG5760 ou SG6060, peut considérablement améliorer les performances. Consultez votre architecte de solutions NetApp StorageGRID pour obtenir de l'aide sur le dimensionnement.

Pour sa règle de protection des données, StorageGRID utilise une règle de gestion du cycle de vie intégrée afin de gérer et de protéger les données. Les règles ILM sont évaluées dans une règle de haut en bas. Nous avons implémenté la politique ILM présentée dans le tableau suivant :

[cols="1a,1a,1a"]
|===
| Règle ILM | Qualificatifs | Comportement d'ingestion 


 a| 
Code d'effacement 2+1
 a| 
Objets de plus de 200 Ko
 a| 
Équilibré



 a| 
2 copies
 a| 
Tous les objets
 a| 
Double allocation

|===
La règle ILM 2 Copy est la règle par défaut. La règle Erasure Coding 2+1 a été appliquée pour ce test à tout objet de 200 Ko ou plus. La règle par défaut a été appliquée aux objets inférieurs à 200 Ko. L'application des règles de cette manière est une bonne pratique StorageGRID.

Pour obtenir des informations techniques sur cet environnement de test, consultez la section conception de la solution et meilleures pratiques du https://www.netapp.com/us/media/tr-4831.pdf["Protection des données scale-out NetApp avec CommVault"] rapport technique.



== Spécifications matérielles de la baie StorageGRID

Le tableau suivant décrit le matériel NetApp StorageGRID utilisé dans ce test. L'appliance StorageGRID SG5712 avec mise en réseau 10 Gbits/s est l'option d'entrée de gamme et représente une configuration de base. Éventuellement, le SG5712 peut être configuré pour une mise en réseau de 25 Gbit/s.

[cols="1a,1a,1a,1a,1a"]
|===
| Sous-jacent | Quantité | Disque | Capacité exploitable | Le réseau 


 a| 
Appliances StorageGRID SG5712
 a| 
4
 a| 
48 x 4 To (disque dur SAS secondaire)
 a| 
136 TO
 a| 
10 Gbit/s

|===
Le choix d'options d'appliance hautes performances, telles que les appliances NetApp StorageGRID SG5760, SG6060 et 100 % Flash SGF6112 peut apporter des avantages significatifs en matière de performance. Consultez votre architecte de solutions NetApp StorageGRID pour obtenir de l'aide sur le dimensionnement.



== Configuration logicielle requise pour CommVault et StorageGRID

Les tableaux suivants répertorient les logiciels requis pour les logiciels CommVault et NetApp StorageGRID installés sur le logiciel VMware à des fins de test. Quatre gestionnaires de transmission de données MediaAgent et un serveur CommServe ont été installés. Lors du test, une mise en réseau de 10 Gbits/s a été mise en œuvre pour l'infrastructure VMware. Le tableau suivant

Le tableau suivant répertorie la configuration système totale requise pour le logiciel CommVault :

[cols="1a,1a,1a,1a,1a,1a"]
|===
| Composant | Quantité | Datastore | Taille | Total | Nombre total d'IOPS requises 


 a| 
Serveur CommServe
 a| 
1
 a| 
OS
 a| 
500 GO
 a| 
500 GO
 a| 
s/o



 a| 
 a| 
 a| 
SQL
 a| 
500 GO
 a| 
500 GO
 a| 
s/o



 a| 
MediaAgent
 a| 
4
 a| 
Processeur virtuel (vCPU)
 a| 
16
 a| 
64
 a| 
s/o



 a| 
 a| 
 a| 
RAM
 a| 
128 GO
 a| 
512
 a| 
s/o



 a| 
 a| 
 a| 
OS
 a| 
500 GO
 a| 
2 TO
 a| 
s/o



 a| 
 a| 
 a| 
Cache d'index
 a| 
2 TO
 a| 
8 TO
 a| 
200+



 a| 
 a| 
 a| 
DDB
 a| 
2 TO
 a| 
8 TO
 a| 
200 000 000 K

|===
Dans l'environnement de test, un nœud d'administration principal virtuel et un nœud de passerelle virtuelle ont été déployés sur VMware sur une baie de stockage NetApp E-Series E2812. Chaque nœud se trouvait sur un serveur distinct avec les exigences minimales relatives à l'environnement de production décrites dans le tableau suivant :

Le tableau suivant répertorie les conditions requises pour les nœuds d'administration virtuelle et les nœuds de passerelle StorageGRID :

[cols="1a,1a,1a,1a,1a"]
|===
| Type de nœud | Quantité | VCPU | RAM | Stockage 


 a| 
Nœud de passerelle
 a| 
1
 a| 
8
 a| 
24 GO
 a| 
LUN de 100 Gb pour le système d'exploitation



 a| 
Nœud d'administration
 a| 
1
 a| 
8
 a| 
24 GO
 a| 
LUN de 100 Gb pour le système d'exploitation

LUN de 200 Go pour les tables de nœuds d'administration

LUN de 200 Go pour le journal d'audit du nœud d'administration

|===